yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: pnp
packageExtensions:
  micromark-extension-mdx-expression@*:
    dependencies:
      acorn: "*"
  remark-mdx@*:
    dependencies:
      unified: "*"
      mdast: "*"
  mdast-util-mdx@*:
    dependencies:
      mdast-util-to-markdown: "*"
      mdast-util-from-markdown: "*"
  mdast-util-mdx-jsx@*:
    dependencies:
      mdast-util-from-markdown: "*"
      "@types/unist": "*"
